// <auto-generated />
using System;
using IncidentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NewProject.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    [Migration("20260713163453_AddIncidentNotes")]
    partial class AddIncidentNotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("Branch");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SSN");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentHistory", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SSN")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("vw_IncidentHistory");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NoteId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentNotes");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Username");

                    b.ToTable("IncidentStatTracking");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IssueId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            IssueId = 1,
                            IsActive = true,
                            Name = "Online Account"
                        },
                        new
                        {
                            IssueId = 2,
                            IsActive = true,
                            Name = "Payment"
                        },
                        new
                        {
                            IssueId = 3,
                            IsActive = true,
                            Name = "Credit Score"
                        },
                        new
                        {
                            IssueId = 4,
                            IsActive = true,
                            Name = "Loan Inquiry"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SolutionId");

                    b.HasIndex("IssueId");

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            SolutionId = 1,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Reset Password"
                        },
                        new
                        {
                            SolutionId = 2,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Unlock Account"
                        },
                        new
                        {
                            SolutionId = 3,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Update Email"
                        },
                        new
                        {
                            SolutionId = 4,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Change Payment Method"
                        },
                        new
                        {
                            SolutionId = 5,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Extension"
                        },
                        new
                        {
                            SolutionId = 6,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Reversal"
                        },
                        new
                        {
                            SolutionId = 7,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Request Credit Report"
                        },
                        new
                        {
                            SolutionId = 8,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Dispute Credit Score"
                        },
                        new
                        {
                            SolutionId = 9,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Payoff Quote"
                        },
                        new
                        {
                            SolutionId = 10,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Refinance Information"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany("StatTrackings")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.HasOne("IncidentManagement.Models.Issue", "Issue")
                        .WithMany("Solutions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Navigation("StatTrackings");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
