// <auto-generated />
using System;
using IncidentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NewProject.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    [Migration("20260909143138_ConsolidateDatabases")]
    partial class ConsolidateDatabases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentManagement.Models.BranchLocation", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("BranchId");

                    b.ToTable("BranchLocations");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "123 Main Street",
                            BranchCode = "0101",
                            BranchName = "Downtown Financial Center",
                            City = "Springfield",
                            IsActive = true,
                            Phone = "2175550101",
                            State = "IL",
                            ZipCode = "62701"
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "456 West Oak Avenue",
                            BranchCode = "0202",
                            BranchName = "Westside Lending Branch",
                            City = "Riverside",
                            IsActive = true,
                            Phone = "9515550202",
                            State = "CA",
                            ZipCode = "92501"
                        },
                        new
                        {
                            BranchId = 3,
                            Address = "789 North Park Blvd",
                            BranchCode = "0303",
                            BranchName = "Northgate Financial",
                            City = "Portland",
                            IsActive = true,
                            Phone = "5035550303",
                            State = "OR",
                            ZipCode = "97201"
                        },
                        new
                        {
                            BranchId = 4,
                            Address = "321 East Commerce St",
                            BranchCode = "0404",
                            BranchName = "Eastside Loan Center",
                            City = "Nashville",
                            IsActive = true,
                            Phone = "6155550404",
                            State = "TN",
                            ZipCode = "37201"
                        },
                        new
                        {
                            BranchId = 5,
                            Address = "654 South Elm Street",
                            BranchCode = "0505",
                            BranchName = "Southpark Branch",
                            City = "Charlotte",
                            IsActive = true,
                            Phone = "7045550505",
                            State = "NC",
                            ZipCode = "28201"
                        },
                        new
                        {
                            BranchId = 6,
                            Address = "987 Lakewood Drive",
                            BranchCode = "0606",
                            BranchName = "Lakewood Financial Center",
                            City = "Denver",
                            IsActive = true,
                            Phone = "3035550606",
                            State = "CO",
                            ZipCode = "80201"
                        },
                        new
                        {
                            BranchId = 7,
                            Address = "147 Midtown Plaza",
                            BranchCode = "0707",
                            BranchName = "Midtown Lending Office",
                            City = "Atlanta",
                            IsActive = true,
                            Phone = "4045550707",
                            State = "GA",
                            ZipCode = "30301"
                        },
                        new
                        {
                            BranchId = 8,
                            Address = "258 River Road",
                            BranchCode = "0808",
                            BranchName = "Riverside Branch",
                            City = "Columbus",
                            IsActive = true,
                            Phone = "6145550808",
                            State = "OH",
                            ZipCode = "43201"
                        },
                        new
                        {
                            BranchId = 9,
                            Address = "369 Highland Avenue",
                            BranchCode = "0909",
                            BranchName = "Highland Park Office",
                            City = "Birmingham",
                            IsActive = true,
                            Phone = "2055550909",
                            State = "AL",
                            ZipCode = "35201"
                        },
                        new
                        {
                            BranchId = 10,
                            Address = "741 Greenfield Parkway",
                            BranchCode = "1010",
                            BranchName = "Greenfield Lending Center",
                            City = "Greenville",
                            IsActive = true,
                            Phone = "8645551010",
                            State = "SC",
                            ZipCode = "29601"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.CallTip", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TipId");

                    b.HasIndex("IssueId");

                    b.ToTable("CallTips");

                    b.HasData(
                        new
                        {
                            TipId = 1,
                            IssueId = 1,
                            SortOrder = 1,
                            Tip = "Verify the customer's identity before making any account changes — ask for full name, SSN last 4, and date of birth."
                        },
                        new
                        {
                            TipId = 2,
                            IssueId = 1,
                            SortOrder = 2,
                            Tip = "If the customer is locked out, confirm whether they are using the correct username/email before resetting."
                        },
                        new
                        {
                            TipId = 3,
                            IssueId = 1,
                            SortOrder = 3,
                            Tip = "For password resets, remind the customer the link expires in 24 hours and to check their spam folder."
                        },
                        new
                        {
                            TipId = 4,
                            IssueId = 1,
                            SortOrder = 4,
                            Tip = "If the customer reports unauthorized access, escalate immediately to a supervisor."
                        },
                        new
                        {
                            TipId = 5,
                            IssueId = 2,
                            SortOrder = 1,
                            Tip = "Confirm the payment amount and due date before processing any changes."
                        },
                        new
                        {
                            TipId = 6,
                            IssueId = 2,
                            SortOrder = 2,
                            Tip = "If a payment was returned, ask the customer to verify their bank account and routing number."
                        },
                        new
                        {
                            TipId = 7,
                            IssueId = 2,
                            SortOrder = 3,
                            Tip = "Payment extensions must be approved by a supervisor — do not promise an extension without approval."
                        },
                        new
                        {
                            TipId = 8,
                            IssueId = 2,
                            SortOrder = 4,
                            Tip = "Always confirm the customer's preferred payment method and check if it is on file."
                        },
                        new
                        {
                            TipId = 9,
                            IssueId = 3,
                            SortOrder = 1,
                            Tip = "Explain that we report to credit bureaus monthly and changes may take 30-60 days to reflect."
                        },
                        new
                        {
                            TipId = 10,
                            IssueId = 3,
                            SortOrder = 2,
                            Tip = "If the customer disputes a credit report item, direct them to dispute through the credit bureau directly."
                        },
                        new
                        {
                            TipId = 11,
                            IssueId = 3,
                            SortOrder = 3,
                            Tip = "Do not make promises about credit score improvements — explain factors that generally affect scores."
                        },
                        new
                        {
                            TipId = 12,
                            IssueId = 3,
                            SortOrder = 4,
                            Tip = "If requesting a credit report, confirm the customer's mailing address is current before sending."
                        },
                        new
                        {
                            TipId = 13,
                            IssueId = 4,
                            SortOrder = 1,
                            Tip = "Verify the customer's current loan balance and payoff amount before discussing refinance options."
                        },
                        new
                        {
                            TipId = 14,
                            IssueId = 4,
                            SortOrder = 2,
                            Tip = "For payoff quotes, remind the customer the quote is valid for 10 days and interest accrues daily."
                        },
                        new
                        {
                            TipId = 15,
                            IssueId = 4,
                            SortOrder = 3,
                            Tip = "Refinance inquiries should be referred to the branch manager — do not quote rates directly."
                        },
                        new
                        {
                            TipId = 16,
                            IssueId = 4,
                            SortOrder = 4,
                            Tip = "If the account is charged off, do not discuss settlement options without supervisor approval."
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("Branch");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SSN");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentHistory", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SSN")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("vw_IncidentHistory");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NoteId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentNotes");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Username");

                    b.ToTable("IncidentStatTracking");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IssueId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            IssueId = 1,
                            IsActive = true,
                            Name = "Online Account"
                        },
                        new
                        {
                            IssueId = 2,
                            IsActive = true,
                            Name = "Payment"
                        },
                        new
                        {
                            IssueId = 3,
                            IsActive = true,
                            Name = "Credit Score"
                        },
                        new
                        {
                            IssueId = 4,
                            IsActive = true,
                            Name = "Loan Inquiry"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.LoanAccount", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ChargeOffDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DelinquentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FirstPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("LastDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LastPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanClass")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LoanReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("NetProceeds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NextDueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OriginationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PayoffAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrincipalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ScheduledPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusCodes")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("LoanId");

                    b.ToTable("LoanAccounts");

                    b.HasData(
                        new
                        {
                            LoanId = 1,
                            AccountNumber = "10001",
                            AmountDue = 175.00m,
                            BranchCode = "0404",
                            DelinquentAmount = 0m,
                            FirstName = "JOHN",
                            FirstPaymentDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomePhone = "6155554321",
                            LastDueDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "MILLER",
                            LastPaymentAmount = 175.00m,
                            LastPaymentDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanAmount = 3500.00m,
                            LoanClass = "1",
                            LoanReference = "0404-10001",
                            MobilePhone = "6155551234",
                            NetProceeds = 2800.00m,
                            NextDueAmount = 175.00m,
                            NextDueDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OriginationDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayoffAmount = 1920.00m,
                            PrincipalBalance = 1850.00m,
                            ScheduledPayment = 175.00m,
                            StatusCodes = "PB",
                            StreetAddress = "415 MAPLE STREET, NASHVILLE TN 37201",
                            TaxId = "123456789"
                        },
                        new
                        {
                            LoanId = 2,
                            AccountNumber = "20001",
                            AmountDue = 890.00m,
                            BranchCode = "0505",
                            ChargeOffDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DelinquentAmount = 890.00m,
                            FirstName = "SARAH",
                            FirstPaymentDate = new DateTime(2021, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastDueDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "JOHNSON",
                            LastPaymentAmount = 210.00m,
                            LastPaymentDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanAmount = 5000.00m,
                            LoanClass = "1",
                            LoanReference = "0505-20001",
                            MobilePhone = "7045552345",
                            NetProceeds = 4200.00m,
                            OriginationDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayoffAmount = 3450.00m,
                            PrincipalBalance = 3100.00m,
                            ScheduledPayment = 210.00m,
                            StatusCodes = "CO",
                            StreetAddress = "822 OAK LANE, CHARLOTTE NC 28201",
                            TaxId = "234567890"
                        },
                        new
                        {
                            LoanId = 3,
                            AccountNumber = "30001",
                            AmountDue = 0m,
                            BranchCode = "0707",
                            DelinquentAmount = 0m,
                            FirstName = "ROBERT",
                            FirstPaymentDate = new DateTime(2022, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomePhone = "4045556543",
                            LastDueDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "DAVIS",
                            LastPaymentAmount = 120.00m,
                            LastPaymentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanAmount = 2000.00m,
                            LoanClass = "1",
                            LoanReference = "0707-30001",
                            MobilePhone = "4045553456",
                            NetProceeds = 1650.00m,
                            OriginationDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayoffAmount = 0m,
                            PrincipalBalance = 0m,
                            ScheduledPayment = 120.00m,
                            StatusCodes = "PO",
                            StreetAddress = "331 PEACHTREE RD, ATLANTA GA 30301",
                            TaxId = "345678901"
                        },
                        new
                        {
                            LoanId = 4,
                            AccountNumber = "40001",
                            AmountDue = 0m,
                            BranchCode = "0202",
                            DelinquentAmount = 0m,
                            FirstName = "MARIA",
                            FirstPaymentDate = new DateTime(2020, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastDueDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "GARCIA",
                            LastPaymentAmount = 95.00m,
                            LastPaymentDate = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanAmount = 1500.00m,
                            LoanClass = "1",
                            LoanReference = "0202-40001",
                            MobilePhone = "9515554567",
                            NetProceeds = 1200.00m,
                            OriginationDate = new DateTime(2020, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayoffAmount = 0m,
                            PrincipalBalance = 0m,
                            ScheduledPayment = 95.00m,
                            StatusCodes = "PO",
                            StreetAddress = "19 SUNSET BLVD, RIVERSIDE CA 92501",
                            TaxId = "456789012"
                        },
                        new
                        {
                            LoanId = 5,
                            AccountNumber = "40002",
                            AmountDue = 195.00m,
                            BranchCode = "0202",
                            DelinquentAmount = 0m,
                            FirstName = "MARIA",
                            FirstPaymentDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastDueDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "GARCIA",
                            LastPaymentAmount = 195.00m,
                            LastPaymentDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanAmount = 4200.00m,
                            LoanClass = "1",
                            LoanReference = "0202-40002",
                            MobilePhone = "9515554567",
                            NetProceeds = 3500.00m,
                            NextDueAmount = 195.00m,
                            NextDueDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OriginationDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PayoffAmount = 3310.00m,
                            PrincipalBalance = 3200.00m,
                            ScheduledPayment = 195.00m,
                            StatusCodes = "PB",
                            StreetAddress = "19 SUNSET BLVD, RIVERSIDE CA 92501",
                            TaxId = "456789012"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("FeesApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanReference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("PaidThroughDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrincipalApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            ConfirmationNumber = "10011001",
                            FeesApplied = 0m,
                            LoanReference = "0404-10001",
                            PaidThroughDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 142.00m,
                            TransactionAmount = 175.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            ConfirmationNumber = "10011002",
                            FeesApplied = 0m,
                            LoanReference = "0404-10001",
                            PaidThroughDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 140.00m,
                            TransactionAmount = 175.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 3,
                            ConfirmationNumber = "10011003",
                            FeesApplied = 0m,
                            LoanReference = "0404-10001",
                            PaidThroughDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 138.00m,
                            TransactionAmount = 175.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 4,
                            ConfirmationNumber = "10011004",
                            FeesApplied = 0m,
                            LoanReference = "0404-10001",
                            PaidThroughDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 136.00m,
                            TransactionAmount = 175.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 5,
                            ConfirmationNumber = "10011005",
                            FeesApplied = 0m,
                            LoanReference = "0404-10001",
                            PaidThroughDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 134.00m,
                            TransactionAmount = 175.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 6,
                            ConfirmationNumber = "20011001",
                            FeesApplied = 0m,
                            LoanReference = "0505-20001",
                            PaidThroughDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 160.00m,
                            TransactionAmount = 210.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 7,
                            ConfirmationNumber = "20011002",
                            FeesApplied = 0m,
                            LoanReference = "0505-20001",
                            PaidThroughDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 158.00m,
                            TransactionAmount = 210.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 8,
                            ConfirmationNumber = "20011003",
                            FeesApplied = 0m,
                            LoanReference = "0505-20001",
                            PaidThroughDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 156.00m,
                            TransactionAmount = 210.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2023, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 9,
                            ConfirmationNumber = "20011004",
                            FeesApplied = 25.00m,
                            LoanReference = "0505-20001",
                            PrincipalApplied = 0m,
                            TransactionAmount = 25.00m,
                            TransactionCode = "LF",
                            TransactionDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 10,
                            ConfirmationNumber = "30011001",
                            FeesApplied = 0m,
                            LoanReference = "0707-30001",
                            PaidThroughDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 119.00m,
                            TransactionAmount = 120.00m,
                            TransactionCode = "PO",
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 11,
                            ConfirmationNumber = "30011002",
                            FeesApplied = 0m,
                            LoanReference = "0707-30001",
                            PaidThroughDate = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 116.00m,
                            TransactionAmount = 120.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 12,
                            ConfirmationNumber = "30011003",
                            FeesApplied = 0m,
                            LoanReference = "0707-30001",
                            PaidThroughDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 113.00m,
                            TransactionAmount = 120.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 13,
                            ConfirmationNumber = "40011001",
                            FeesApplied = 0m,
                            LoanReference = "0202-40001",
                            PaidThroughDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 94.00m,
                            TransactionAmount = 95.00m,
                            TransactionCode = "PO",
                            TransactionDate = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 14,
                            ConfirmationNumber = "40011002",
                            FeesApplied = 0m,
                            LoanReference = "0202-40001",
                            PaidThroughDate = new DateTime(2021, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 92.00m,
                            TransactionAmount = 95.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 15,
                            ConfirmationNumber = "40021001",
                            FeesApplied = 0m,
                            LoanReference = "0202-40002",
                            PaidThroughDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 155.00m,
                            TransactionAmount = 195.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 16,
                            ConfirmationNumber = "40021002",
                            FeesApplied = 0m,
                            LoanReference = "0202-40002",
                            PaidThroughDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 153.00m,
                            TransactionAmount = 195.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 17,
                            ConfirmationNumber = "40021003",
                            FeesApplied = 0m,
                            LoanReference = "0202-40002",
                            PaidThroughDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrincipalApplied = 151.00m,
                            TransactionAmount = 195.00m,
                            TransactionCode = "PA",
                            TransactionDate = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SolutionId");

                    b.HasIndex("IssueId");

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            SolutionId = 1,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Reset Password"
                        },
                        new
                        {
                            SolutionId = 2,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Unlock Account"
                        },
                        new
                        {
                            SolutionId = 3,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Update Email"
                        },
                        new
                        {
                            SolutionId = 4,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Change Payment Method"
                        },
                        new
                        {
                            SolutionId = 5,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Extension"
                        },
                        new
                        {
                            SolutionId = 6,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Reversal"
                        },
                        new
                        {
                            SolutionId = 7,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Request Credit Report"
                        },
                        new
                        {
                            SolutionId = 8,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Dispute Credit Score"
                        },
                        new
                        {
                            SolutionId = 9,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Payoff Quote"
                        },
                        new
                        {
                            SolutionId = 10,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Refinance Information"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.CallTip", b =>
                {
                    b.HasOne("IncidentManagement.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany("StatTrackings")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.HasOne("IncidentManagement.Models.Issue", "Issue")
                        .WithMany("Solutions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Navigation("StatTrackings");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
