// <auto-generated />
using System;
using IncidentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NewProject.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    [Migration("20260713170956_AddCallTips")]
    partial class AddCallTips
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentManagement.Models.CallTip", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TipId");

                    b.HasIndex("IssueId");

                    b.ToTable("CallTips");

                    b.HasData(
                        new
                        {
                            TipId = 1,
                            IssueId = 1,
                            SortOrder = 1,
                            Tip = "Verify the customer's identity before making any account changes — ask for full name, SSN last 4, and date of birth."
                        },
                        new
                        {
                            TipId = 2,
                            IssueId = 1,
                            SortOrder = 2,
                            Tip = "If the customer is locked out, confirm whether they are using the correct username/email before resetting."
                        },
                        new
                        {
                            TipId = 3,
                            IssueId = 1,
                            SortOrder = 3,
                            Tip = "For password resets, remind the customer the link expires in 24 hours and to check their spam folder."
                        },
                        new
                        {
                            TipId = 4,
                            IssueId = 1,
                            SortOrder = 4,
                            Tip = "If the customer reports unauthorized access, escalate immediately to a supervisor."
                        },
                        new
                        {
                            TipId = 5,
                            IssueId = 2,
                            SortOrder = 1,
                            Tip = "Confirm the payment amount and due date before processing any changes."
                        },
                        new
                        {
                            TipId = 6,
                            IssueId = 2,
                            SortOrder = 2,
                            Tip = "If a payment was returned, ask the customer to verify their bank account and routing number."
                        },
                        new
                        {
                            TipId = 7,
                            IssueId = 2,
                            SortOrder = 3,
                            Tip = "Payment extensions must be approved by a supervisor — do not promise an extension without approval."
                        },
                        new
                        {
                            TipId = 8,
                            IssueId = 2,
                            SortOrder = 4,
                            Tip = "Always confirm the customer's preferred payment method and check if it is on file."
                        },
                        new
                        {
                            TipId = 9,
                            IssueId = 3,
                            SortOrder = 1,
                            Tip = "Explain that we report to credit bureaus monthly and changes may take 30-60 days to reflect."
                        },
                        new
                        {
                            TipId = 10,
                            IssueId = 3,
                            SortOrder = 2,
                            Tip = "If the customer disputes a credit report item, direct them to dispute through the credit bureau directly."
                        },
                        new
                        {
                            TipId = 11,
                            IssueId = 3,
                            SortOrder = 3,
                            Tip = "Do not make promises about credit score improvements — explain factors that generally affect scores."
                        },
                        new
                        {
                            TipId = 12,
                            IssueId = 3,
                            SortOrder = 4,
                            Tip = "If requesting a credit report, confirm the customer's mailing address is current before sending."
                        },
                        new
                        {
                            TipId = 13,
                            IssueId = 4,
                            SortOrder = 1,
                            Tip = "Verify the customer's current loan balance and payoff amount before discussing refinance options."
                        },
                        new
                        {
                            TipId = 14,
                            IssueId = 4,
                            SortOrder = 2,
                            Tip = "For payoff quotes, remind the customer the quote is valid for 10 days and interest accrues daily."
                        },
                        new
                        {
                            TipId = 15,
                            IssueId = 4,
                            SortOrder = 3,
                            Tip = "Refinance inquiries should be referred to the branch manager — do not quote rates directly."
                        },
                        new
                        {
                            TipId = 16,
                            IssueId = 4,
                            SortOrder = 4,
                            Tip = "If the account is charged off, do not discuss settlement options without supervisor approval."
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SSN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("Branch");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SSN");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentHistory", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SSN")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("vw_IncidentHistory");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NoteId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentNotes");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Username");

                    b.ToTable("IncidentStatTracking");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IssueId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            IssueId = 1,
                            IsActive = true,
                            Name = "Online Account"
                        },
                        new
                        {
                            IssueId = 2,
                            IsActive = true,
                            Name = "Payment"
                        },
                        new
                        {
                            IssueId = 3,
                            IsActive = true,
                            Name = "Credit Score"
                        },
                        new
                        {
                            IssueId = 4,
                            IsActive = true,
                            Name = "Loan Inquiry"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SolutionId");

                    b.HasIndex("IssueId");

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            SolutionId = 1,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Reset Password"
                        },
                        new
                        {
                            SolutionId = 2,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Unlock Account"
                        },
                        new
                        {
                            SolutionId = 3,
                            IsActive = true,
                            IssueId = 1,
                            Name = "Update Email"
                        },
                        new
                        {
                            SolutionId = 4,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Change Payment Method"
                        },
                        new
                        {
                            SolutionId = 5,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Extension"
                        },
                        new
                        {
                            SolutionId = 6,
                            IsActive = true,
                            IssueId = 2,
                            Name = "Payment Reversal"
                        },
                        new
                        {
                            SolutionId = 7,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Request Credit Report"
                        },
                        new
                        {
                            SolutionId = 8,
                            IsActive = true,
                            IssueId = 3,
                            Name = "Dispute Credit Score"
                        },
                        new
                        {
                            SolutionId = 9,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Payoff Quote"
                        },
                        new
                        {
                            SolutionId = 10,
                            IsActive = true,
                            IssueId = 4,
                            Name = "Refinance Information"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Models.CallTip", b =>
                {
                    b.HasOne("IncidentManagement.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentNote", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.IncidentStatTracking", b =>
                {
                    b.HasOne("IncidentManagement.Models.Incident", "Incident")
                        .WithMany("StatTrackings")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Models.Solution", b =>
                {
                    b.HasOne("IncidentManagement.Models.Issue", "Issue")
                        .WithMany("Solutions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IncidentManagement.Models.Incident", b =>
                {
                    b.Navigation("StatTrackings");
                });

            modelBuilder.Entity("IncidentManagement.Models.Issue", b =>
                {
                    b.Navigation("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
